# Default configuration for DirectShootingPlanner
urdf_path: "panda_description"
target_link_name: "panda_hand_tcp"
path_length_weight: 1.0
particle_matching_weight: 50.0
max_iterations: 100
visualize: true
ee2tip_offset: [0.0, 0.0, -0.09]
max_num_timesteps_for_optimization: 50
